<!doctype html>
<html <?php language_attributes(); ?>>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class('whaledive-home'); ?>><?php wp_body_open(); ?>
<main class="wd-page">
  <header class="wd-header"><div class="wd-shell"><div class="wd-nav"><a class="wd-brand" href="/"><img src="https://whaledivecentre.com/wp-content/themes/theme-travel-master/assets/logo.jpg" alt="Whale Dive Centre"><span>Whale Dive Centre</span></a><button class="wd-hamburger" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button><nav class="wd-menu" id="wd-mobile-menu"><a href="/">Home</a><a href="/courses/">Courses</a><a href="/equipment/">Equipment</a><a href="/about/">About</a><?php if(is_user_logged_in()){ $u=wp_get_current_user(); echo '<a href="/member-dashboard/" class="wd-nav-member">Dashboard</a>'; } else { echo '<a href="/member-login/" class="wd-nav-member">Login</a>'; } ?></nav></div></div></header>

  <!-- HERO -->
  <section class="wd-hero"><div class="wd-shell wd-hero-grid"><div><span class="wd-kicker">Scuba training, gear support & dive community</span><h1>Dive Beyond<br>the Surface.</h1><p>Professional scuba training, ocean-minded community, curated dive equipment, and safer dive habits from our Jakarta base to your next underwater adventure.</p><div class="wd-actions"><a class="wd-btn" href="/courses/">Explore Courses</a><a class="wd-btn alt" href="/member-register/">Join Our Community</a></div></div><aside class="wd-panel"><div class="wd-tabs"><div class="wd-tab active">Course Plan</div><div class="wd-tab">Community</div></div><form class="wd-form" id="wd-hero-course-form" action="/about/#contact-form" method="get"><div class="wd-form-row"><div><label>Your Name</label><input type="text" name="name" placeholder="Your name" required></div><div><label>WhatsApp</label><input type="tel" name="whatsapp" placeholder="+62 ..." required></div></div><div><label>Certification Level</label><select name="cert"><option>Open Water</option><option>Advanced Open Water</option><option>Rescue Diver</option><option>Divemaster</option><option>Instructor Course</option></select></div><div><label>Preferred Schedule</label><input type="text" name="schedule" placeholder="Weekend / weekday / custom"></div><div><label>Group Size</label><select name="group"><option>Solo diver</option><option>2-4 divers</option><option>Private group</option></select></div><button type="submit" class="wd-btn alt">Request Course Plan</button></form><div class="wd-stats"><div class="wd-stat"><b>4</b><span>Training paths</span></div><div class="wd-stat"><b>5+</b><span>Course levels</span></div><div class="wd-stat"><b>1:1</b><span>Gear fitting</span></div></div></aside></div></section>

  <section class="wd-proof-strip"><div class="wd-shell"><span>Certified training guidance</span><span>Small-group skill progression</span><span>Gear fitting support</span><span>Jakarta dive centre base</span></div></section>    <section class="wd-section white wd-authentic"><div class="wd-shell"><div class="wd-divider"><h2 class="wd-title">Built for calmer, better-prepared divers</h2></div><p class="wd-sub">Training, equipment support, and trip planning are handled as one connected experience so every diver understands the plan before getting in the water.</p><div class="wd-auth-grid"><article class="wd-auth-card wd-auth-training"><span>Training</span><h3>Skill-first course sessions</h3><p>Clear briefings, repeated practice, and instructor-led progression before open-water confidence.</p></article><article class="wd-auth-card wd-auth-gear"><span>Gear fitting</span><h3>Comfort before checkout</h3><p>Mask fit, exposure protection, BCD sizing, and computer setup support from the crew.</p></article><article class="wd-auth-card wd-auth-trip"><span>Community</span><h3>Trips planned around conditions</h3><p>Site choice, group size, and diver readiness come before rushing a schedule.</p></article></div><p class="wd-photo-note">Real training, crew, and product photos can replace these visual panels once the final media pack is available.</p></div></section>    <!-- WELCOME -->
  <section class="wd-section light wd-center"><div class="wd-shell"><h2 class="wd-title">Welcome to <em>Whale Dive Centre</em></h2><p class="wd-sub">Your gateway to the underwater world. We combine professional scuba training, quality gear, small-group guidance, and a strong passion for marine conservation.</p><div class="wd-checks"><div class="wd-check">Certified Instructors</div><div class="wd-check">Small Group Training</div><div class="wd-check">Safety Focused</div><div class="wd-check">Community Driven</div></div></div></section>

  <!-- AFFILIATIONS -->
  <section class="wd-section white wd-center"><div class="wd-shell"><div class="wd-divider"><h2 class="wd-title">Our Affiliations</h2></div><p class="wd-sub">Training pathways and dive standards aligned with globally recognized scuba organizations.</p><div class="wd-logos"><div class="wd-logo-pill">PADI<span>Recreational training</span></div><div class="wd-logo-pill">SSI<span>Dive education</span></div><div class="wd-logo-pill">NAUI<span>Safety standards</span></div><div class="wd-logo-pill">TDI<span>Technical pathway</span></div></div></div></section>

  <!-- COURSES -->
  <section id="courses" class="wd-section wd-dark wd-center"><div class="wd-shell"><div class="wd-divider"><h2 class="wd-title">Our Dive Courses</h2></div><p class="wd-sub">A structured pathway from your first breath underwater to professional-level leadership.</p><div class="wd-course-grid"><?php $courses=[['Open Water','Beginner','3-4 days','Your first certification to dive safely with a buddy.','open-water-diver'],['Advanced Open Water','Next level','2 days','Build confidence with deeper dives, navigation, and specialty skills.','advanced-open-water'],['Rescue Diver','Safety','2-3 days','Learn prevention, response, and real-world rescue thinking.','rescue-diver'],['Divemaster','Pro track','Flexible','Lead dives, assist classes, and grow into a dive professional.','divemaster'],['Instructor Course','Teach','Custom','Prepare to teach, mentor, and guide new divers.','instructor-course']]; foreach($courses as $i=>$c): ?><article class="wd-course-card"><div class="wd-course-no">0<?php echo $i+1; ?></div><h3><?php echo esc_html($c[0]); ?></h3><div class="wd-course-meta"><span><?php echo esc_html($c[1]); ?></span><span><?php echo esc_html($c[2]); ?></span></div><p><?php echo esc_html($c[3]); ?></p><a href="/courses/">View course</a></article><?php endforeach; ?></div><div class="wd-section-cta"><a class="wd-btn" href="/courses/">View All Courses</a></div></div></section>

  <!-- DIVE SITES HIDDEN -->
<!-- EQUIPMENT -->
  <section id="equipment" class="wd-section white wd-center wd-eq"><div class="wd-shell"><div class="wd-divider"><h2 class="wd-title">Scuba Equipment</h2></div><p class="wd-sub">Quality gear for training, fun dives, and safer underwater comfort. Buy or rent through the crew.</p><div class="wd-equipment-grid"><?php $eq=[['Masks','Clear vision and reliable fit','M'],['Wetsuits','Thermal comfort for longer dives','W'],['BCD','Buoyancy control and trim support','B'],['Regulators','Smooth breathing and safe air delivery','R'],['Fins','Efficient movement with less fatigue','F'],['Dive Computers','Track depth, time, and safety stops','D']]; foreach($eq as $e): ?><article class="wd-equip-card"><div class="wd-equip-icon"><?php echo esc_html($e[2]); ?></div><h3><?php echo esc_html($e[0]); ?></h3><p><?php echo esc_html($e[1]); ?></p><a href="/equipment/">Browse gear</a></article><?php endforeach; ?></div><div class="wd-section-cta"><a class="wd-btn alt" href="/equipment/">View All Equipment</a></div></div></section>

  <!-- SOCIAL PROOF (NEW) -->
  <section class="wd-section wd-proof wd-center"><div class="wd-shell"><span class="wd-kicker">Trusted by Divers</span><h2 class="wd-title">What Our Community Says</h2><div class="wd-reviews-grid">
    <article class="wd-review-card"><div class="wd-review-stars">★★★★★</div><p>"The crew made my first open water course feel safe and calm. Small group, patient instructors, and the gear was in great condition."</p><div class="wd-review-author"><b>Sarah M.</b><span>Open Water Diver</span></div></article>
    <article class="wd-review-card"><div class="wd-review-stars">★★★★★</div><p>"Best dive centre in Bali for serious training. Did my Divemaster here and the mentorship was world-class. Highly recommend."</p><div class="wd-review-author"><b>Marco R.</b><span>PADI Divemaster</span></div></article>
    <article class="wd-review-card"><div class="wd-review-stars">★★★★★</div><p>"Bought my first mask and fins here. The crew helped me find the right fit before I even got in the water. Great service."</p><div class="wd-review-author"><b>Ayu P.</b><span>Active Diver</span></div></article>
  </div></div></section>

  <!-- ARTICLES -->
  <section id="articles" class="wd-section wd-articles"><div class="wd-shell"><div class="wd-article-head"><div><span class="wd-kicker">Featured Article</span><h2 class="wd-title">Dive Stories & Ocean Notes</h2><p class="wd-sub">Curated reads for new divers, gear buyers, and ocean-minded community members.</p></div><a class="wd-btn" href="/blog/">Read Blog</a></div><div class="wd-article-grid"><article class="wd-featured-card"><span>Featured</span><h3>How to Prepare for Your First Open Water Course</h3><p>What to expect before pool sessions, ocean dives, equipment fitting, and the habits that make new divers feel calm underwater.</p><a href="/blog/">Read article</a></article><article class="wd-mini-article"><b>Gear Guide</b><h3><a href="/mask-fit-tips-buying-first-scuba-mask/">Mask fit tips before buying your first scuba mask</a></h3></article><article class="wd-mini-article"><b>Safety</b><h3><a href="/slow-ascents-buoyancy-control/">Why slow ascents and buoyancy control matter</a></h3></article><article class="wd-mini-article"><b>Community</b><h3><a href="/better-dive-habits-small-groups/">Building better dive habits with small groups</a></h3></article></div></div></section>

  <!-- MEMBERSHIP CTA -->
  <section id="membership" class="wd-section wd-community wd-center"><div class="wd-shell"><span class="wd-kicker">Member Portal</span><h2 class="wd-title">Join the Whale Dive Community</h2><p class="wd-sub">Track your courses, manage certifications, purchase equipment, and connect with the crew — all from your member dashboard.</p><div class="wd-trust-row"><div><b>Course tracking</b><span>Enrollment to certification</span></div><div><b>Equipment shop</b><span>Buy or rent gear online</span></div><div><b>Cert portfolio</b><span>All your dive cards in one place</span></div></div><a class="wd-btn alt" href="/member-register/">Create Free Account</a></div></section>

  <!-- FOOTER -->
  <footer id="contact" class="wd-footer"><div class="wd-shell"><div class="wd-footer-top"><div class="wd-footer-brand"><span class="wd-footer-kicker">Ready to dive?</span><h2>Whale Dive Centre</h2><p>Dive training, community trips, equipment support, and ocean-minded experiences for safer adventures below the surface.</p><a class="wd-btn alt" href="/about/#contact-form">Start Inquiry</a></div><nav class="wd-footer-col"><h3>Explore</h3><a href="/courses/">Dive Courses</a><a href="/equipment/">Scuba Equipment</a><a href="/about/">About Us</a><a href="/blog/">Blog</a></nav><nav class="wd-footer-col"><h3>Courses</h3><a href="/course/open-water-diver/">Open Water</a><a href="/course/advanced-open-water/">Advanced Open Water</a><a href="/course/rescue-diver/">Rescue Diver</a><a href="/course/divemaster/">Divemaster</a><a href="/course/instructor-course/">Instructor</a></nav><div class="wd-footer-col"><h3>Contact</h3><p>Email: info@whaledivecentre.com</p><p>WhatsApp: <?php echo esc_html(get_option("wdc_whatsapp_number", "(021) 27939068")); ?></p><p>Jl. Tanah Kusir II No.3, RT.10/RW.9, Kby. Lama Sel., Kec. Kebayoran Lama, Kota Jakarta Selatan, DKI Jakarta 12240</p><div class="wd-social"><a href="https://www.instagram.com/whaledivecentre.id?igsh=YjE1Z3o4NjBmcjAy" target="_blank" rel="noopener" aria-label="Facebook">FB</a><a href="https://www.instagram.com/whaledivecentre.id?igsh=YjE1Z3o4NjBmcjAy" target="_blank" rel="noopener" aria-label="Instagram">IG</a><a href="https://www.instagram.com/whaledivecentre.id?igsh=YjE1Z3o4NjBmcjAy" target="_blank" rel="noopener" aria-label="YouTube">YT</a><a href="https://www.instagram.com/whaledivecentre.id?igsh=YjE1Z3o4NjBmcjAy" target="_blank" rel="noopener" aria-label="TikTok">TT</a></div></div></div><div class="wd-footer-bottom"><span>© <?php echo date('Y'); ?> Whale Dive Centre. All rights reserved.</span><span>PADI / SSI / NAUI / TDI training pathways</span> | <a href="/privacy-policy/" style="color:rgba(255,255,255,.6);text-decoration:none;font-size:13px">Privacy Policy</a> | <a href="/terms/" style="color:rgba(255,255,255,.6);text-decoration:none;font-size:13px">Terms of Service</a></div></div></footer>
</main>
<script>document.addEventListener("DOMContentLoaded",function(){var b=document.querySelector(".wd-hamburger"),m=document.querySelector(".wd-menu");if(!b||!m)return;b.addEventListener("click",function(){var open=document.body.classList.toggle("wd-menu-open");b.setAttribute("aria-expanded",open?"true":"false")});m.querySelectorAll("a").forEach(function(a){a.addEventListener("click",function(){document.body.classList.remove("wd-menu-open");b.setAttribute("aria-expanded","false")})})})</script><script>
document.addEventListener('DOMContentLoaded', function(){
  var form = document.getElementById('wd-hero-course-form');
  if(!form) return;
  form.addEventListener('submit', function(event){
    if(!form.checkValidity()) return;
    event.preventDefault();
    var data = new FormData(form);
    var name = (data.get('name') || '').toString().trim();
    var phone = (data.get('whatsapp') || '').toString().trim();
    var cert = (data.get('cert') || '').toString().trim();
    var schedule = (data.get('schedule') || '').toString().trim();
    var group = (data.get('group') || '').toString().trim();
    var msg = 'Hi Whale Dive Centre, my name is ' + name + '. I want a course plan. WhatsApp: ' + phone + '. Certification: ' + cert + '. Schedule: ' + (schedule || 'flexible') + '. Group: ' + group + '.';
    window.location.href = 'tel:+622127939068';
  });
});
</script>
<?php wp_footer(); ?></body></html>
