<?php
/**
 * Template Name: Whale Dive Login
 */
?><!doctype html>
<html <?php language_attributes(); ?>>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class('whaledive-inner whaledive-login wdc-auth-page'); ?>><?php wp_body_open(); ?>
<main class="wd-page">
  <header class="wd-header"><div class="wd-shell"><div class="wd-nav"><a class="wd-brand" href="/"><img class="wd-brand-logo" src="<?php echo esc_url(get_template_directory_uri() . '/assets/wdc-navbar-logo.jpg?v=20260514b'); ?>" alt="Whale Dive Centre"><span>Whale Dive Centre</span></a><button class="wd-hamburger" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button><nav class="wd-menu" id="wd-mobile-menu"><a href="/" data-nav="home">Home</a><a href="/courses/" data-nav="courses">Courses</a><a href="/equipment/" data-nav="equipment">Equipment</a><a href="/blog/" data-nav="blog">Blog</a><?php if(is_user_logged_in()){ $u=wp_get_current_user(); echo '<a href="/dashboard/" class="wd-nav-member">Dashboard</a>'; } else { echo '<a href="/member-login/" class="wd-nav-member is-active" aria-current="page">Login</a>'; } ?></nav></div></div></header>
  <section class="wdc-auth-hero"><div class="wd-shell wdc-auth-grid"><div class="wdc-auth-copy"><a class="wdc-auth-back" href="/">← Back to Home</a><span class="wd-kicker">Member access</span><h1>Welcome back.</h1><p>Log in to manage course progress, gear requests, certifications, and crew updates from one calm dashboard.</p><div class="wdc-auth-proof"><div><b>Course</b><span>Tracking</span></div><div><b>Gear</b><span>Requests</span></div><div><b>Crew</b><span>Updates</span></div></div></div><aside class="wdc-auth-card"><h2>Log in</h2><p>Use your Whale Dive Centre account details.</p><?php if(isset($_GET['login']) && $_GET['login'] === 'failed'): ?><div class="wdc-auth-alert">Login failed. Please check your credentials.</div><?php endif; ?><form class="wdc-auth-form" method="post" action="<?php echo esc_url(home_url('/wp-login.php')); ?>"><input type="hidden" name="redirect_to" value="<?php echo esc_url(home_url('/dashboard/')); ?>"><div class="wdc-auth-field"><label>Email or username</label><input type="text" name="log" autocomplete="username" required></div><div class="wdc-auth-field"><label>Password</label><div class="wd-password-wrap"><input id="wd-login-password" type="password" name="pwd" autocomplete="current-password" required><button class="wd-password-toggle" type="button" data-target="wd-login-password">Show</button></div></div><div class="wdc-auth-row"><label><input type="checkbox" name="rememberme" value="forever"> Remember me</label><a href="<?php echo esc_url(wp_lostpassword_url()); ?>">Forgot?</a></div><button class="wdc-auth-submit" type="submit">Log In</button></form><p class="wdc-auth-switch">Don't have an account? <a href="/member-register/">Create one</a></p></aside></div></section>
  <footer id="contact" class="wd-footer"><div class="wd-shell"><div class="wd-footer-top"><div class="wd-footer-brand"><span class="wd-footer-kicker">Ready to dive?</span><h2>Whale Dive Centre</h2><p>Dive training, community trips, equipment support, and ocean-minded experiences for safer adventures below the surface.</p><a class="wd-btn alt" href="/contact/">Start Inquiry</a></div><nav class="wd-footer-col"><h3>Explore</h3><a href="/courses/">Dive Courses</a><a href="/equipment/">Scuba Equipment</a><a href="/contact/">About Us</a><a href="/blog/">Blog</a></nav><nav class="wd-footer-col"><h3>Courses</h3><a href="/courses/open-water-diver/">Open Water</a><a href="/courses/advanced-open-water/">Advanced Open Water</a><a href="/courses/rescue-diver/">Rescue Diver</a><a href="/courses/divemaster/">Divemaster</a><a href="/courses/underwater-photography/">Photography</a></nav><div class="wd-footer-col"><h3>Contact</h3><p>Email: info@whaledivecentre.com</p><p>Phone: (021) 27939068</p><p>Jl. Tanah Kusir II No.3, Kebayoran Lama, Jakarta Selatan 12240</p><div class="wd-social"><a href="https://www.instagram.com/whaledivecentre.id?igsh=YjE1Z3o4NjBmcjAy" target="_blank" rel="noopener" aria-label="Instagram">Instagram</a></div></div></div><div class="wd-footer-bottom"><span>&copy; <?php echo date('Y'); ?> Whale Dive Centre. All rights reserved.</span><span>PADI / SSI / NAUI / TDI training pathways</span></div></div></footer>
</main>
<script>document.addEventListener("click",function(e){var b=e.target.closest(".wd-password-toggle");if(!b)return;var i=document.getElementById(b.dataset.target);if(!i)return;var show=i.type==="password";i.type=show?"text":"password";b.textContent=show?"Hide":"Show";});</script><?php wp_footer(); ?></body></html>